type Dict = typeof ar;

const ar = {
  dashboard: "لوحة التحكم",
  menu: "قائمة الطعام",
  branches: "الفروع",
  tables: "الطاولات",
  orders: "الطلبات",
  reviews: "التقييمات",
  settings: "الإعدادات",
  viewSite: "مشاهدة الموقع",
  signOut: "تسجيل الخروج",
  adminPanel: "لوحة التحكم",
  welcomeBack: "مرحباً بعودتك",
  dashboardTitle: "لوحة التحكم",
  menuEditor: "محرر القائمة",
  addCategory: "إضافة قسم",
  addItem: "إضافة صنف",
  editItem: "تعديل صنف",
  create: "إنشاء",
  update: "تحديث",
  cancel: "إلغاء",
  delete: "حذف",
  save: "حفظ",
  arabicName: "الاسم بالعربية",
  englishName: "الاسم بالإنجليزية",
  arabicDesc: "الوصف بالعربية",
  englishDesc: "الوصف بالإنجليزية",
  price: "السعر",
  image: "صورة",
  upload: "رفع",
  badge: "شارة",
  none: "لا شيء",
  popular: "رائج",
  spicy: "حار",
  hasSizes: "بأحجام متعددة",
  sizes: "الأحجام",
  addSize: "+ إضافة حجم",
  items: "أصناف",
  hidden: "مخفي",
  categories: "أقسام",
  deleteCategoryConfirm: "حذف هذا القسم وجميع أصنافه؟",
  branch: "فرع",
  branchesTitle: "الفروع",
  edit: "تعديل",
  createBranch: "إنشاء فرع جديد",
  deleteBranchConfirm: "حذف هذا الفرع؟ سيتم حذف جميع الطاولات والبيانات المرتبطة به.",
  branchNumber: "رقم الفرع",
  nameAr: "الاسم بالعربية",
  nameEn: "الاسم بالإنجليزية",
  addressAr: "العنوان بالعربية",
  addressEn: "العنوان بالإنجليزية",
  phone: "الهاتف",
  whatsapp: "واتساب",
  creating: "جارٍ الإنشاء...",
  tablesTitle: "الطاولات",
  inWord: "في",
  addOne: "إضافة واحدة",
  generateMany: "إنشاء مجموعة",
  printQR: "طباعة QR",
  generate: "إنشاء",
  count: "العدد",
  from: "من",
  tableNumber: "رقم الطاولة",
  inactive: "غير نشط",
  activate: "تنشيط",
  deactivate: "إلغاء التنشيط",
  noTables: "لا توجد طاولات في هذا الفرع بعد. استخدم الأزرار أعلاه للإضافة.",
  noBranches: "لا توجد فروع بعد. أنشئ فرعاً أولاً قبل إدارة الطاولات.",
  goToBranches: "الذهاب إلى الفروع",
  printAllQR: "طباعة جميع رموز QR",
  activeOrders: "الطلبات النشطة",
  history: "السجل",
  noActiveOrders: "لا توجد طلبات نشطة",
  newOrdersAppear: "ستظهر الطلبات الجديدة هنا مباشرة",
  noServedOrders: "لا توجد طلبات مكتملة بعد",
  preparing: "قيد التحضير",
  ready: "جاهز",
  served: "تم التسليم",
  new: "جديد",
  table: "طاولة",
  soundOn: "الصوت مفعل",
  soundOff: "الصوت معطل",
  reviewsTitle: "التقييمات",
  pending: "قيد الانتظار",
  approved: "مقبول",
  deleteReviewConfirm: "حذف هذا التقييم؟",
  noReviews: "لا توجد تقييمات بعد.",
  settingsTitle: "الإعدادات",
  systemConfig: "إعدادات النظام",
  orderHistoryTTL: "مدة الاحتفاظ بسجل الطلبات (ساعات)",
  ttlDescription: "يتم حذف الطلبات المكتملة تلقائياً بعد هذه المدة. النطاق: 1-72.",
  liveTracking: "تتبع الطلبات المباشر للعملاء",
  liveTrackingDesc: "يعرض للعملاء حالة الطلب مباشرة (تم الاستلام → قيد التحضير → جاهز → تم التسليم).",
  soundAlerts: "تنبيهات صوتية للموظفين",
  soundAlertsDesc: "يصدر صوت عند وصول طلب جديد على لوحة التحكم.",
  on: "مفعل",
  off: "معطل",
  saving: "جارٍ الحفظ...",
  loginTitle: "تسجيل الدخول",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  signingIn: "جارٍ تسجيل الدخول...",
  signIn: "تسجيل الدخول",
  backToDashboard: "العودة إلى لوحة التحكم",
  somethingWentWrong: "حدث خطأ ما",
  unexpectedError: "حدث خطأ غير متوقع. حاول مرة أخرى.",
  tryAgain: "حاول مرة أخرى",
  loading: "جارٍ التحميل...",
  print: "طباعة",
  backToTables: "العودة إلى الطاولات",
  allBranches: "كل الفروع",
  printPageTitle: "طباعة رموز QR",
  tablesCount: "طاولات",
  printInstructions: "اطبع وقص على طول الخطوط المنقطة للصق الطاولات",
  noTablesToPrint: "لا توجد طاولات للطباعة. اختر فرعاً أعلاه.",
  tableQRLabel: "طاولة",
  language: "اللغة",
  dashboardSubtitle: "مرحباً بعودتك",
  quickActions: "إجراءات سريعة",
  manageOrders: "إدارة الطلبات النشطة",
  editMenuItems: "تعديل أصناف القائمة",
  manageTables: "إدارة الطاولات والفروع",
};

const en: Dict = {
  dashboard: "Dashboard",
  menu: "Menu",
  branches: "Branches",
  tables: "Tables",
  orders: "Orders",
  reviews: "Reviews",
  settings: "Settings",
  viewSite: "View Site",
  signOut: "Sign Out",
  adminPanel: "Admin Panel",
  welcomeBack: "Welcome back",
  dashboardTitle: "Dashboard",
  menuEditor: "Menu Editor",
  addCategory: "Add Category",
  addItem: "Add Item",
  editItem: "Edit Item",
  create: "Create",
  update: "Update",
  cancel: "Cancel",
  delete: "Delete",
  save: "Save",
  arabicName: "Arabic Name",
  englishName: "English Name",
  arabicDesc: "Description (AR)",
  englishDesc: "Description (EN)",
  price: "Price",
  image: "Image",
  upload: "Upload",
  badge: "Badge",
  none: "None",
  popular: "Popular",
  spicy: "Spicy",
  hasSizes: "Has Multiple Sizes",
  sizes: "Sizes",
  addSize: "+ Add Size",
  items: "Items",
  hidden: "Hidden",
  categories: "Categories",
  deleteCategoryConfirm: "Delete this category and all its items?",
  branch: "Branch",
  branchesTitle: "Branches",
  edit: "Edit",
  createBranch: "Create New Branch",
  deleteBranchConfirm: "Delete this branch? All associated tables and data will be removed.",
  branchNumber: "Branch Number",
  nameAr: "Arabic Name",
  nameEn: "English Name",
  addressAr: "Arabic Address",
  addressEn: "English Address",
  phone: "Phone",
  whatsapp: "WhatsApp",
  creating: "Creating...",
  tablesTitle: "Tables",
  inWord: "in",
  addOne: "Add One",
  generateMany: "Generate Many",
  printQR: "Print QR",
  generate: "Generate",
  count: "Count",
  from: "From",
  tableNumber: "Table Number",
  inactive: "Inactive",
  activate: "Activate",
  deactivate: "Deactivate",
  noTables: "No tables in this branch yet. Use the buttons above to add some.",
  noBranches: "No branches exist yet. Create a branch first before managing tables.",
  goToBranches: "Go to Branches",
  printAllQR: "Print All QR Codes",
  activeOrders: "Active Orders",
  history: "History",
  noActiveOrders: "No active orders",
  newOrdersAppear: "New orders will appear here in real time",
  noServedOrders: "No served orders yet",
  preparing: "Preparing",
  ready: "Ready",
  served: "Served",
  new: "New",
  table: "Table",
  soundOn: "Sound ON",
  soundOff: "Sound OFF",
  reviewsTitle: "Reviews",
  pending: "Pending",
  approved: "Approved",
  deleteReviewConfirm: "Delete this review?",
  noReviews: "No reviews yet.",
  settingsTitle: "Settings",
  systemConfig: "System Configuration",
  orderHistoryTTL: "Order History TTL (hours)",
  ttlDescription: "Served orders are auto-deleted after this many hours. Range: 1–72.",
  liveTracking: "Customer Live Order Tracking",
  liveTrackingDesc: "Shows customers real-time order status (received → preparing → ready → served).",
  soundAlerts: "Staff Sound Alerts",
  soundAlertsDesc: "Plays a sound when a new order arrives on the dashboard.",
  on: "ON",
  off: "OFF",
  saving: "Saving...",
  loginTitle: "Login",
  email: "Email",
  password: "Password",
  signingIn: "Signing in...",
  signIn: "Sign In",
  backToDashboard: "Back to Dashboard",
  somethingWentWrong: "Something went wrong",
  unexpectedError: "An unexpected error occurred. Please try again.",
  tryAgain: "Try again",
  loading: "Loading...",
  print: "Print",
  backToTables: "Back to Tables",
  allBranches: "All Branches",
  printPageTitle: "Print QR Codes",
  tablesCount: "Tables",
  printInstructions: "Print and cut along dashed lines for table stickers",
  noTablesToPrint: "No tables to print. Select a branch above.",
  tableQRLabel: "Table",
  language: "Language",
  dashboardSubtitle: "Welcome back",
  quickActions: "Quick Actions",
  manageOrders: "Manage active orders",
  editMenuItems: "Edit menu items",
  manageTables: "Manage tables & branches",
};

const LANG_KEY = "getboatkeg-admin-lang";

function loadLang(): "ar" | "en" {
  if (typeof window === "undefined") return "ar";
  const stored = window.localStorage.getItem(LANG_KEY);
  return stored === "en" ? "en" : "ar";
}

export const t = { ...ar } as Dict;

export function switchAdminLang(lang: "ar" | "en") {
  Object.assign(t, lang === "en" ? en : ar);
  if (typeof window !== "undefined") {
    window.localStorage.setItem(LANG_KEY, lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    window.dispatchEvent(new Event("admin-lang-changed"));
  }
}

if (typeof window !== "undefined" && loadLang() === "en") {
  switchAdminLang("en");
}

export function getAdminLang(): "ar" | "en" {
  return loadLang();
}
