ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "branchId" INTEGER;
ALTER TABLE "Review" ADD CONSTRAINT "Review_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;
